name: wallpaper_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.1.0+12

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  path_provider: ^2.0.13
  permission_handler: ^11.3.1
  intl: ^0.19.0
  cloud_firestore: ^4.4.3
  font_awesome_flutter: ^10.4.0
  dots_indicator: ^3.0.0
  carousel_slider: ^4.2.1
  sliding_up_panel: ^2.0.0+1
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  google_sign_in: ^6.0.1
  firebase_auth: ^4.2.9
  connectivity: ^3.0.6
  cached_network_image: ^3.2.3
  launch_review: ^3.0.1
  awesome_dialog: ^3.0.2
  shimmer: ^3.0.0
  wallpaper: ^1.0.7
  firebase_core: ^2.7.0
  rounded_loading_button: ^2.0.9
  google_mobile_ads: ^5.0.0
  onesignal_flutter: ^5.1.3
  flutter_native_splash: ^2.1.1
  dio: ^5.4.2+1
  open_filex: ^4.3.2
  flutter_local_notifications: ^17.0.0
  flutter_web_browser: ^0.17.1
  fluttertoast: ^8.2.1
  google_fonts: ^6.2.1
  rounded_loading_button_plus: ^3.0.1
  # facebook_audience_network: ^1.0.1
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.0.0


  
flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "assets/images/icon.png"


flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"
  android: true
  ios: false
  android_12:


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    
    - assets/images/
 
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
